const questions=[
{tag:"專案／任務開始",text:"面對一個全新且時間緊迫的團隊任務，你的第一反應是？",answers:[["A","迅速釐清核心目標，規劃優先順序並分配分工。"],["B","關心大家的狀態，確保大家都有信心並主動鼓舞士氣。"],["C","確認細節流程、時間表與品質標準，確保不犯錯。"],["D","保持彈性，隨時準備應對可能發生的各種變數。"]]},
{tag:"突發狀況／變數",text:"執行過程中突然遇到重大變數，你會怎麼做？",answers:[["A","立刻重新評估策略，迅速下達替代決策並帶領團隊轉向。"],["B","安撫大家的情緒，確保團隊不恐慌、維持氣氛和諧。"],["C","深入分析變數原因，盤點受影響的細節並修訂標準作業流程。"],["D","冷靜接受現況，靈活找出目前最務實、可行的替代方案。"]]},
{tag:"成員低潮／效率低",text:"團隊中有人進度落後或動力不足、陷入低潮，你的應對方式是？",answers:[["A","直接給予明確的時間點與目標，必要時重新調整分工以保證產出。"],["B","主動私下關心，傾聽對方的困難並給予情感上的支持與鼓勵。"],["C","幫忙找出他工作流程中的卡關點，給予結構化的方法建議。"],["D","順其自然，給予對方空間，並默默分擔部分可隨機處理的工作。"]]},
{tag:"意見分歧／衝突",text:"團隊討論時大家意見分歧、爭執不下，你會如何處理？",answers:[["A","以最終目標為導向，果斷拍板做出決定以打破僵局。"],["B","擔任溝通橋樑，尋求折衷點並化解對立氣氛。"],["C","列出各方案的優缺點與數據邏輯，用客觀事實來說服大家。"],["D","觀察局勢發展，等大家冷靜後再提出務實的融合作法。"]]},
{tag:"溝通與破冰",text:"跟新加入或比較內向沉默的夥伴合作時，你習慣怎麼互動？",answers:[["A","給予明確的指示與期待，讓他知道目標在哪裡。"],["B","熱情邀請他參與討論，主動聊天拉近距離。"],["C","提供清晰完整的文件或資訊，讓他有條理地熟悉業務。"],["D","不給對方太大的壓力，在隨常合作中自然建立默契。"]]},
{tag:"成果查核／品質",text:"對於「做完」與「做好」的標準，你的內心哲學是？",answers:[["A","天下武功唯快不破，先快速完成核心目標，再迭代優化。"],["B","大家合作愉快、過程圓滿，比追求極致的完美更重要。"],["C","嚴格把關品質，細節決定成敗，絕不接受瑕疵品。"],["D","視情況而定，在現有條件下做出最高 CP 值的成品即可。"]]},
{tag:"團隊成功與反思",text:"任務圓滿結束後，你最希望帶給團隊什麼？",answers:[["A","滿滿的成就感與突破目標的戰果。"],["B","溫暖的團隊凝聚力與良好的夥伴情誼。"],["C","完善的結案復盤與可傳承的經驗流程。"],["D","輕鬆踏實的安心感與隨遇而安的彈性。"]]},
{tag:"個人風格自我認知",text:"朋友或同事最常怎麼形容你的工作／做事風格？",answers:[["A","很有主見、目標明確、效率極高。"],["B","很體貼、好相處，是團隊的開心果與潤滑劑。"],["C","很細心、講求邏輯、做事讓人非常放心。"],["D","很冷靜、脾氣好、遇到突發狀況很隨機應變。"]]}];
const mapping={A:"strategy",B:"warmth",C:"rigor",D:"adapt"},labels={strategy:"策略",warmth:"暖心",rigor:"嚴謹",adapt:"應變"};
const profiles={strategy:{title:"策略導向型",en:"The Direction Setter",emoji:"🎯",summary:"你習慣先看目標，再快速決定優先順序，帶大家往前走。",strengths:["決策速度快，目標清楚","推進力強，能快速建立方向","面對混亂時容易抓住重點"],blinds:["可能太快做決定，忽略成員感受","容易把速度放在細節之前","高效率有時會讓別人感到壓力"],growth:"做決定前，多確認一次成員狀況與關鍵細節，會讓你的帶隊更完整。"},warmth:{title:"暖心協作型",en:"The People Connector",emoji:"🤝",summary:"你會先顧好人與關係，讓團隊在有安全感的情況下一起往前走。",strengths:["同理心強，容易建立信任","擅長維持團隊氣氛","能讓較安靜的成員感到被看見"],blinds:["可能過度在意和諧，不容易做強硬決定","有時會延後處理衝突","容易把別人的需求放在自己之前"],growth:"在需要時練習更明確地設定界線、期限與責任分工。"},rigor:{title:"嚴謹執行型",en:"The Reliable Builder",emoji:"🧩",summary:"你習慣把流程、細節與品質顧好，讓事情穩穩地完成。",strengths:["細節敏銳，品質穩定","流程與風險意識高","讓人覺得可靠、放心"],blinds:["可能花太多時間確認細節","容易對自己或別人要求過高","遇到模糊情況時可能較難快速決定"],growth:"練習分辨「一定要做到」與「做到夠好即可」，能讓你兼顧品質與速度。"},adapt:{title:"沉穩應變型",en:"The Adaptive Anchor",emoji:"🛡️",summary:"你擅長在變動中維持冷靜，找到最務實、可行的處理方式。",strengths:["抗壓性高，遇到變化不慌張","臨場反應佳，能快速找替代方案","給團隊穩定感"],blinds:["可能因為太隨機應變而前期規劃不足","有時會避免正面衝突","容易邊走邊看，忽略長期安排"],growth:"保留彈性的同時，先準備最低限度的優先順序與備案，會更穩。"}};
let current=0,picks=[];const $=id=>document.getElementById(id);const show=id=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0)};
$('startBtn').onclick=()=>{current=0;picks=[];renderQ();show('quizScreen')};$('backBtn').onclick=()=>{if(current===0){show('startScreen');return}current--;picks.pop();renderQ()};$('restartBtn').onclick=()=>{current=0;picks=[];show('startScreen')};$('copyBtn').onclick=copyResult;$('submitBtn').onclick=submitResult;
function renderQ(){const q=questions[current],pct=Math.round((current+1)/questions.length*100);$('questionCount').textContent=`第 ${current+1} / ${questions.length} 題`;$('progressPercent').textContent=`${pct}%`;$('progressBar').style.width=`${pct}%`;$('questionTag').textContent=`【${q.tag}】`;$('questionText').textContent=q.text;$('answers').innerHTML='';q.answers.forEach(([k,t])=>{const b=document.createElement('button');b.className='answer';b.innerHTML=`<span class="answer-key">${k}</span><span>${t}</span>`;b.onclick=()=>pick(k);$('answers').appendChild(b)})}
function pick(k){picks.push(k);if(current<questions.length-1){current++;renderQ();window.scrollTo(0,0)}else{renderResult();show('resultScreen')}}
function scores(){const s={strategy:0,warmth:0,rigor:0,adapt:0};picks.forEach(k=>s[mapping[k]]++);return s}
function result(s){const m=Math.max(...Object.values(s)),tops=Object.keys(s).filter(k=>s[k]===m);return {kind:tops.length===1?'single':tops.length===2?'mixed':'balanced',keys:tops}}
function renderResult(){const s=scores(),r=result(s),p=profiles[r.keys[0]];if(r.kind==='single'){$('resultTitle').textContent=p.title;$('resultEn').textContent=p.en;$('resultEmoji').textContent=p.emoji;$('resultSummary').textContent=p.summary}else if(r.kind==='mixed'){$('resultTitle').textContent=`${labels[r.keys[0]]} × ${labels[r.keys[1]]} 混合型`;$('resultEn').textContent='Balanced Dual Style';$('resultEmoji').textContent='🔀';$('resultSummary').textContent=`你的最高向度同時落在「${labels[r.keys[0]]}」與「${labels[r.keys[1]]}」。`}else{$('resultTitle').textContent='平衡型';$('resultEn').textContent='Balanced Team Style';$('resultEmoji').textContent='⚖️';$('resultSummary').textContent='你的分數分布較平均，代表你不容易只用單一方式處理所有情境。'}const ps=r.keys.slice(0,2).map(k=>profiles[k]);$('strengthList').innerHTML=[...new Set(ps.flatMap(x=>x.strengths))].slice(0,3).map(x=>`<li>${x}</li>`).join('');$('blindList').innerHTML=[...new Set(ps.flatMap(x=>x.blinds))].slice(0,3).map(x=>`<li>${x}</li>`).join('');$('growthText').textContent=r.kind==='single'?p.growth:'保留你的多元反應優勢，同時練習辨認：當下最需要的是目標、關係、品質，還是彈性。';$('scoreText').textContent=`策略 ${s.strategy}｜暖心 ${s.warmth}｜嚴謹 ${s.rigor}｜應變 ${s.adapt}`;drawRadar(s);window.__lastResult={scores:s,result:r,title:$('resultTitle').textContent}}
function drawRadar(s){const c=$('radar'),x=c.getContext('2d'),w=c.width,h=c.height,cx=w/2,cy=h/2+8,R=130,max=questions.length,a=[["strategy","策略",-Math.PI/2],["warmth","暖心",0],["rigor","嚴謹",Math.PI/2],["adapt","應變",Math.PI]];x.clearRect(0,0,w,h);x.strokeStyle='#d8dee8';for(let ring=1;ring<=4;ring++){let r=R*ring/4;x.beginPath();a.forEach(([, ,ang],i)=>{let px=cx+Math.cos(ang)*r,py=cy+Math.sin(ang)*r;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.stroke()}a.forEach(([,lab,ang])=>{x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(ang)*R,cy+Math.sin(ang)*R);x.stroke();x.fillStyle='#52627a';x.font='22px sans-serif';x.textAlign='center';x.fillText(lab,cx+Math.cos(ang)*(R+42),cy+Math.sin(ang)*(R+28))});x.beginPath();a.forEach(([k,,ang],i)=>{let r=R*s[k]/max,px=cx+Math.cos(ang)*r,py=cy+Math.sin(ang)*r;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.fillStyle='rgba(79,70,229,.18)';x.fill();x.strokeStyle='#4f46e5';x.lineWidth=4;x.stroke()}
function txt(){const r=window.__lastResult;if(!r)return'';return `我的小組長 Team Style：${r.title}
策略 ${r.scores.strategy}｜暖心 ${r.scores.warmth}｜嚴謹 ${r.scores.rigor}｜應變 ${r.scores.adapt}

這只是團隊情境中的偏好，不是能力高低判定。`}
async function copyResult(){try{await navigator.clipboard.writeText(txt());$('copyBtn').textContent='✓ 已複製';setTimeout(()=>$('copyBtn').textContent='複製測驗結果',1500)}catch{alert(txt())}}
async function submitResult(){const ep=window.RESULTS_ENDPOINT||'';if(!ep){$('submitStatus').textContent='尚未設定 Google Sheet 回傳網址。請依 README 設定 config.js。';return}const r=window.__lastResult,p={timestamp:new Date().toISOString(),name:$('nameInput').value.trim(),className:$('classInput').value.trim(),result:r.title,strategy:r.scores.strategy,warmth:r.scores.warmth,rigor:r.scores.rigor,adapt:r.scores.adapt};$('submitStatus').textContent='傳送中…';try{await fetch(ep,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(p)});$('submitStatus').textContent='✓ 已送出結果'}catch{$('submitStatus').textContent='送出失敗，請稍後再試。'}}